### PR TITLE
log: initialize platform handler earlier

### PR DESCRIPTION
**Pull request by benoit-pierre**
Do it before loading plugins, so the user get some feedback on errors.

Note: this still leave Windows users without feedback if an error occurs during the initialization (no platform specific log handler).

### CODE REVIEW

**Comment by benoit-pierre** [comment]
It looks like we could use [plyer](https://pypi.python.org/pypi/plyer) for notifications on Windows:
2017-03-10-030616_1280x1007_scrot

**Comment by benoit-pierre** [comment]
I pushed some commits to do just that.

**Comment by benoit-pierre** [comment]
And it looks like the Windows build does not work... Looking into it.

**Comment by benoit-pierre** [comment]
Using the new distribution works fine however, so I guess it's another PyInstaller issue?

**Comment by morinted** [comment]
I love PyInstaller.

**Pull request merged**
