### PR TITLE
fix for PyPI release

### PR DESCRIPTION
**Pull request by benoit-pierre**
I had to change back the project name to lower case, to match the existing name used on PyPI.

Note to devs: make sure to delete `Plover.egg-info` from you tree to avoid duplicate distributions info.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
I updated the classifiers. Might be time to change the "Development Status" from "4 - Beta" to "5 - Production/Stable", no?

**Comment by morinted** [comment]
Yes, for sure :D

**Comment by benoit-pierre** [comment]
Done, we're stable!

**Comment by morinted** [comment]
The readme could really use a refresh sometime, though we may need to update the Italian translation at the same time.

> Plover is not mature software.

**Comment by benoit-pierre** [comment]
> The readme could really use a refresh sometime, though we may need to update the Italian translation at the same time.

Spanish!

> Plover is not mature software. Once running, it will interpret all keystrokes...

How about changing it too:

> Once Plover is running, it will interpret all keystrokes...

?

**Comment by morinted** [comment]
That sounds like a good change. Maybe it would be good to minimize the read me entirely and link out to external sources like the wiki and the homepage instead, and then link to the OS-specific documentation.

**Pull request merged**
