### PR TITLE
setup: minor metadata cleanup

### PR DESCRIPTION
**Pull request by benoit-pierre**
Fix warning when checking the source distribution with `twine check`.

### CODE REVIEW

**Comment by user202729** [comment]
With https://github.com/openstenoproject/plover/pull/1197 should this be text/markdown...

But then, currently the long_description is only the short string in `plover/__init__.py`, which is also the thing shown on pypi main page (what's the purpose of it being put there rather than all in setup.cfg and leave that file empty? On a related note, the copyright has not been updated for ages)

**Comment by benoit-pierre** [comment]
Well, the content type does not really matter, since as you noticed we only fill it from the (not that long) string in `plover/__init__.py`. We may want to go back to using the readme, in which case will change it to Markdown, yes.

You're right that a copyright update is overdue...

**Comment by morinted** [comment]
Do you want to update the copyright year in this PR?

**Comment by benoit-pierre** [comment]
I'm preparing a big PR that depends on a number of those small PRs, so I would prefer to do that in another PR.

**Comment by benoit-pierre** [comment]
I'll go ahead an merge this.

**Pull request merged**
