### PR TITLE
Improve OSX `send_key_combination`

### PR DESCRIPTION
**Pull request by benoit-pierre**
Use `key_combo.KEYNAME_TO_CHAR`. This address the last point of #533.

Note: untested!

### CODE REVIEW

**Comment by Achim63** [comment]
It doesn't help my cause, unfortunately. I still cannot use e.g. #bracketleft, #bracketright, #braceleft and #braceright, which used to work fine, now they just put out 8, 9, 5 and 6 (the key combination to get the right sign would be alt+8, alt+9 etc.).

**Comment by morinted** [comment]
It was a decision that we made that the "symbol" keys correspond to their base keys from now on.

So the behavior you described is correct…the correct combo would be {#alt(bracketleft)} or {#option(bracketleft)}. This is to prevent ambiguity when you nest these sorts of keys inside modifiers. If you are just trying to send bracket left, you can use the Unicode symbols instead of combos, since they are well supported now.

The symbol names were useful when we didn't have full Unicode support…but now it's available cross all platforms. The key combo keynames are only used now to identify physical keys on the keyboard.

**Comment by Achim63** [comment]
{#alt(bracketleft)} doesn't make sense to me. And I'm really pissed that I'd have to go through my entire dictionary to search for this kind of stuff and change the entries. Guess I'm back to 3.0.0 for now.

**Comment by morinted** [comment]
Why not define your entries as strings like `"{^}[{^}"` or `"{#alt(8)}"`?

**Comment by Achim63** [comment]
"{{^}"  or "{^}}" don't work. No output at all.

**Comment by morinted** [comment]
You'd need to escape the brace: `{\{^}` if you are adding until the add translation dialogue, or `{\\{^}` if editing by hand.

**Comment by Achim63** [comment]
The only reference people have is here: https://sites.google.com/site/ploverdoc/appendix-the-dictionary-format - and that wont work any more.

**Comment by morinted** [comment]
That can be updated → it's already incomplete by a long shot.

**Comment by Achim63** [comment]
"{#alt(8)}" is no good as well – as soon as I switch input source to e.g. US, it wont work any more. I'd expect the dictionaries to have the same output no matter what my qwerty/z keyboard is set to. As mentioned before, mac_keyboard.py does give the right keycodes, no matter which language I picked in system preferences.

**Comment by morinted** [comment]
So what should `{#Shift(braceleft)}` do on each layout? Either way key
combos are not 100% portable. The strings are meant to be "{^}\\{{^}"

**Comment by benoit-pierre** [comment]
The goal of combos is to simulate shortcuts, by simulating a series of key press/release events, so depending on the layout, the keys change (and some are not available). If you want to send a specific character, you should use the normal text output: it's here for that, it's portable (it will automatically map the character if not available on Linux, send Unicode in Windows,...). As already stated, if you're particular issue is that a character does not work (like "à"), then it's a bug with the way we handle the Keyboard layout on Mac, and we need to fix that so you don't have to use a hack (a key combo) instead.

**Pull request merged**
