### PR TITLE
switch distributions to Python 3.8 and update requirements

### PR DESCRIPTION
**Pull request by benoit-pierre**
Note: I updated `hidapi` to `0.10.0.post1` and not `0.10.1` because the later breaks the AppImage build (it looks like linuxdeploy does not like the `manylinux2014` wheel).

### CODE REVIEW

**Comment by morinted** [comment]
I tested on an older Mac version (10.12, Sierra) and got similar no-UI behavior as Glen saw. The notifications still appear but it seems like QT isn't compatible. Tested on 10.15 and it all works.

**Comment by benoit-pierre** [comment]
Any trace? I did use the latest PyQt5 version with what looks like a compatible ABI: `PyQt5-5.15.0-5.15.0-cp35.cp36.cp37.cp38-abi3-macosx_10_6_intel.whl`

**Comment by benoit-pierre** [comment]
Does the build from master work on that old Mac?

**Comment by benoit-pierre** [comment]
Alternate py38 build with the version of PyQt5 as master here: https://github.com/benoit-pierre/plover/actions/runs/712398418

**Comment by morinted** [comment]
Here's the version on master's traceback

```
2021-04-02 14:44:12,891 [MainThread] ERROR: error loading gui plugin: qt (from plover.gui_qt.main)
Traceback (most recent call last):
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/plover/registry.py", line 56, in register_plugin_from_entrypoint
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/plover/gui_qt/main.py", line 4, in <module>
ImportError: dlopen(/Applications/Plover 2.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so, 2): Symbol not found: _futimens
  Referenced from: /Applications/Plover 2.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Plover 2.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
```

This PR's build

```
2021-04-02 14:46:30,070 [MainThread] ERROR: error loading gui plugin: qt (from plover.gui_qt.main)
Traceback (most recent call last):
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.8/site-packages/plover/registry.py", line 56, in register_plugin_from_entrypoint
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.8/site-packages/plover/gui_qt/main.py", line 4, in <module>
ImportError: dlopen(/Applications/Plover.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so, 2): Symbol not found: _futimens
  Referenced from: /Applications/Plover.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Plover.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
```

and the qt5 build with 3.8 you just posted (for some reason still shows 3.6?? Maybe I downloaded something wrong in while doing this over TeamViewer)

```
2021-04-02 14:48:44,589 [MainThread] ERROR: error loading gui plugin: qt (from plover.gui_qt.main)
Traceback (most recent call last):
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/plover/registry.py", line 56, in register_plugin_from_entrypoint
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/plover/gui_qt/main.py", line 4, in <module>
ImportError: dlopen(/Applications/Plover 3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so, 2): Symbol not found: _futimens
  Referenced from: /Applications/Plover 3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Plover 3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
```

**Comment by morinted** [comment]
Confirmed working on Big Sur 👍

**Review by morinted — APPROVED** [review]

**Comment by benoit-pierre** [comment]
Oh well ¯\\_(ツ)_/¯, no way around it if PyQt5 is lying about support for >=10.9...

**Pull request merged**
