### PR TITLE
Add word deletion on empty buffer

### PR DESCRIPTION
**Pull request by morinted**
Addressing issue #105 

Adds an in-built way to handle the empty buffer. After there are no strokes in the buffer, Plover emits "Alt_L(BackSpace)" (Mac) or "Control_L(BackSpace)" (Win & Linux) in order to not halt the user. Also had to include the "{^}" operator because this kind of spacing removes the previous word, not the previous word and its space :)

Could I ask you, @chajadan, to review this? I'm looking for general code style advice, as I think this is very fringe behavior for Plover. Tell me what you think.

Ted

### CODE REVIEW

**Comment by morinted** [comment]
@mighele can I ask you to review this? I imagine you are much more familiar with this part of the code that I am and your feedback would be invaluable.

**Comment by mighele** [comment]
Hi Ted.

Yes I'll look at this

Mike

**Comment by morinted** [comment]
@benoit-pierre can you test this functionality on Linux please? I'll also squash these before any submission.

**Comment by benoit-pierre** [comment]
It does not work great on my setup because of the multiple keyboards, some with colemak with capslock and backspace switched, some with colemak without the switch: somehow depending on the keyboard I use, Plover will send a control+capslock instead of control+backspace...

But that's an unusual setup so let's merge this.

**Comment by benoit-pierre** [comment]
Of course, twice the size may not work on other platforms, and we may have to take other factors, such has the phase of the moon, ambient temperature, etc... So please test, if that magic multiplier is not enough, will increase it...

P.S.: I'm definitively adding wxWidgets to the list of GUI toolkit to avoid.

**Pull request merged**
