### PR TITLE
Fix stentura tests

### PR DESCRIPTION
**Pull request by Elktro**
The merged pull request #200 broke the tests of stentura.py. The tests have been updated and unnecessary tests have been removed. This contains also small coding fixes in stentura.py.

### CODE REVIEW

**Comment by morinted** [comment]
Hi @Elktro, have you looked over #330 yet? Do you have a Stentura machine to test with for whichever change you think is best?

**Comment by Elktro** [comment]
I did not notice #330. I will look into more deeply soon but it seems that it has also some important changes. I have a Stentura SRT 400 which I can surely use for testing.

**Comment by Elktro** [comment]
The pull request #330 as well as master 069d046c1b1962ad8b0f9ae18a482eea3c8a4323 are now merged with this pull request. I have made a quick test with my Stentura SRT 400 and it seems that everything is working okay. Also all the tests run now without failures.

**Comment by morinted** [comment]
@Elktro, how about I merge #330, then you can `git rebase -i` your changes so that you just have your 2 commits in the PR? It would read much more cleanly in the branch history.

**Comment by Elktro** [comment]
Sure thing. I'll do the rebase after the merge.

**Comment by morinted** [comment]
All right, merged #330.

**Comment by Elktro** [comment]
Okay pull request updated. Had to hard reset before rebasing master and then push with force.

**Comment by morinted** [comment]
All right, gave some light feedback.

**Comment by Elktro** [comment]
Thanks for feedback :). I added a named constant and made the test_read_packet_fail more readable. No longer length, length1, length2,... Just data_section_length.

**Comment by morinted** [comment]
All right, thanks for the change. Definitely makes that test a little more readable.

**Pull request merged**
