### PR TITLE
Support Trisquel Linux in bootstrap.sh

### PR DESCRIPTION
**Pull request by hoijui**
works for me. :-)

### CODE REVIEW

**Comment by morinted** [comment]
Thanks for the PR. We are actually considering dropping the OS-specific handling of bootstrap.sh, as opposed to expanding it.

**Comment by hoijui** [comment]
ok...
would it not still make sense to expand it first before removing it?
both for having it in history, and in case the removing is still some in the future, and thus it might be useful for someone in the meantime.
or do you expect merge errors with stuff you have already done in your code/repo?
either way, your choice of course.
not using it is also ok for me.

**Comment by benoit-pierre** [comment]
The PR to remove `bootstrap.sh` has already been submitted (see #772), so the removal should happen sooner than later.

**Comment by hoijui** [comment]
ahh i see, thank you, and i'll close this one then.
if i get a notification (which i should) on merge of your branch, i will check if it works with trisquel ,and add one of these custom version files if necessary.

**Pull request closed without merging**
