### PR TITLE
Allow arpeggiate to be triggered by certain steno keys

### PR DESCRIPTION
**Pull request by KeyboardFire**
Implements #591.

Tested on Arch Linux.

### CODE REVIEW

**Comment by KeyboardFire** [comment]
I've updated the commits in light of the `new_ui` merge (and some other changes that came with it). The PR now works with new UI without any merge conflicts.

**Comment by arxanas** [comment]
I took a look at this PR. What's the difference between these two fields?

screen shot 2016-10-17 at 09 09 52

screen shot 2016-10-17 at 09 09 57

Regardless of what it is, when I try to change the second field and then save the form, the program crashes with this error. I dunno if this is a pre-existing bug might have arisen from the new UI, or if it's because of this patch.

```
2016-10-17 09:12:01,360 [MainThread] WARNING: Keymap is invalid, behavior undefined:

- key a is bound multiple times: ('arpeggiate', 'S-')
Traceback (most recent call last):
  File "/Users/waleed/Workspace/python/plover/plover/gui_qt/config_window.py", line 270, in _on_cell_changed
    self._value[action] = keys.split()
  File "/Users/waleed/Workspace/python/plover/plover/machine/keymap.py", line 128, in __setitem__
    log.warning('Keymap is invalid, behavior undefined:\n\n- ' + '\n- '.join(errors))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1291, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/Users/waleed/Workspace/python/plover/plover/oslayer/log_osx.py", line 27, in emit
    ns.setDelegate_(always_present_delegator)
AttributeError: 'NoneType' object has no attribute 'setDelegate_'
```

**Comment by morinted** [comment]
@KeyboardFire do you have a response for the inquiries from @arxanas ?

I'm also not sure about the UI for this change, how do we communicate the distinction between arpeggiate mode and keys?

**Comment by morinted** [comment]
Closing due to inactivity, please feel free to address feedback and submit a new pull request.

**Pull request closed without merging**
