### PR TITLE
Remove busy loop from the stentura serial port reading

### PR DESCRIPTION
**Pull request by Elktro**
The while loop polling serial port buffer caused 100% CPU usage and was replaced by code that rises the timeout exception if read() method returns less bytes as requested.

### CODE REVIEW

**Comment by morinted** [comment]
Can you confirm this is still a problem in Plover's code and that this fix works? I don't have a Stentura and would love your feedback to help get this into the code base.

**Comment by Elktro** [comment]
I can confirm that this is still problem with the SHA: e5c4aeb91f03f49e5e10d7f54c1dc2c2f35c3f2f. I merged stentura_busy_loop branch to it which fixed the issue.

I have been using this fix for quite some time without any problem with my Stentura 400 SRT machine.

**Comment by morinted** [comment]
Okay, would you like to set the commit's author to have the same email address as you so that the history has your GitHub account?

**Comment by benoit-pierre** [comment]
Note: this change broke the Stentura tests.

**Pull request merged**
