### PR TITLE
* main.json: add 0D and missing n:00 strokes.

### PR DESCRIPTION
**Pull request by JoshuaGrams**
Added a bunch of number strokes which are mentioned in Learn Plover:
- Time strokes for hours from 13:00 to 23:00
- The strokes for hours up to 12 which use the same hand for the modifier.
- #0D for 00

The three strokes which get overwritten are mis-strokes for the versions with a star.

### CODE REVIEW

**Comment by morinted** [comment]
Thanks so much! But as for the same-hand clock strokes, I'm not certain..
 @stenoknight what do you think? I'm mainly uncomfortable with `-B8G` and maybe `-7BG`.

**Comment by JoshuaGrams** [comment]
Yeah, I wasn't sure about that, but they're in Learn Plover. Might be better to fix Learn Plover instead...

**Comment by morinted** [comment]
Mirabai said A-OK! They are some weird strokes but I do remember being confused about Learn Plover being off about it. Thanks for your efforts!

**Comment by benoit-pierre** [comment]
It's too late now, but this probably should have been targeted at the `stable` branch.

**Pull request merged**
