### PR TITLE
Update tox to version 4

### PR DESCRIPTION
**Pull request by greghope667**
## Summary of changes

Updates tox.ini configuration to support building with newer [tox 4](https://tox.wiki/en/latest/upgrading.html).
This is not backwards compatible with tox version 3.

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in news.d. See [documentation](https://github.com/openstenoproject/plover/blob/master/doc/developer_guide.md#making-a-pull-request) for details

I've successfully build & run tests on Linux, this will need testing on Windows and Mac

### CODE REVIEW

**Comment by Robberduckzilla** [comment]
Looks great! Thank you for the PR, G!

**Comment by Robberduckzilla** [comment]
@greghope667 would you mind also adding a news fragment? it's needed to merge a PR, apparently.
in `news.d/bugfix/`, if you add a file called `1592.core.md` and in that, put a 1 sentence description of the changes
e.g. `updated config from supporting tox3 to tox4`

I'll test the changes on windows & mac just now.
Thank you once again for the awesome work!

**Comment by greghope667** [comment]
I've added a news fragment now, thanks.

Tests pass on Linux. Windows has some failing tests for me, but they also fail for me on the master branch so I don't think this change is the culprit.

**Comment by mkrnr** [comment]
Updating tox will remove one obstacle when setting up the dev environment, very nice!
@greghope667 looks like you cancelled the Github actions run? I did a quick test (https://github.com/openstenoproject/plover/pull/1596), the actions should finish successfully. Could you trigger the actions again?

Tomorrow I'll test your changes on macOS, Windows ARM, and Linux ARM. Let's get this PR merged! 💪

**Comment by mkrnr** [comment]
Tested successfully:
* Windows 11 ARM
  * `tox r -e launch`
* Mac OS (ARM but with x86_64 compatibility mode)
  * `arch -x86_64 tox r -e test`
  * `arch -x86_64 tox r -e py3,py39`
  * `arch -x86_64 tox r -e setup -- bdist_app`
  * `arch -x86_64 tox r -e plugins_install -- plover-mod-z`
  * `arch -x86_64 tox r -e launch`


Tested partially successful:
* Windows 11 ARM
  * `tox r -e test`: Failed with the same tests as the master (as already observed by Greg):
    * `test\gui_qt\test_dictionaries_widget.py ..................................FFF`

Tested unsuccessfully:
* Windows 11 ARM
  * `tox r -e setup -- bdist_win`
    * Can't get that to work at all but same issue on the master. Local issue...
* Mac OS (ARM but with x86_64 compatibility mode)
  * `arch -x86_64 tox r -e packaging_checks`
    * `packaging_checks: commands[0]> '{[helpers]functions.sh}' -- packaging_checks
packaging_checks: exit 2 (0.01 seconds) /Users/martin/git/plover-greghope667> '{[helpers]functions.sh}' -- packaging_checks
.pkg: _exit> python /Users/martin/git/plover/venv/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  packaging_checks: FAIL code 2 (15.98=setup[15.98]+cmd[0.01] seconds)
  evaluation failed :( (16.12 seconds)`
    * This can be fixed by replacing `functions.sh =` in tox.ini line 6 with `functions =` as well as all usages of this variable (line 82 and 93). This also fixes the `release_prepare` command
* Linux ARM
  * Not able to test anything because of PyQt5 :(   ...should be fine since you tested Linux yourself. Will buy a computer with Intel chip to install Linux on next days...

If you apply the fix for `functions.sh =` in tox.ini (see above) and all Github Actions are successful, this PR is good to go from my side.

**Comment by greghope667** [comment]
Hi @mkrnr , thanks for looking at the PR and running tests. I've just added the `functions.sh` fix.

The CI job failed (but showed as cancelled) due to [deprecation by GitHub](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) - fixed by #1597

**Comment by sammdot** [comment]
Confirmed that packaging check now passes after the latest change.

I tried to run on Mac with native ARM as well and it seemed to not work at all, which if I understand correctly may have to do with PyQt5, as on Linux. We're possibly doing a migration to PyQt6 soon anyway, so for now this will do.

**Review by sammdot — APPROVED** [review]

**Comment by sammdot** [comment]
Looks good. Thank you all!

**Pull request merged**
