### PR TITLE
update AppVeyor support so we can easily do weekly pre-releases

### PR DESCRIPTION
**Pull request by benoit-pierre**
When pushing to a "weekly" branch, a new pre-release will be automatically deployed to GitHub.

The release will looks [like this](https://github.com/benoit-pierre/plover/releases/tag/weekly-v2.5.8+344.g90c6102).

Note: the version is patched in, so the about dialog will show it.

### CODE REVIEW

**Comment by morinted** [comment]
I'll review this. Is there any way for me to patch in the version to the OSX version?

**Comment by benoit-pierre** [comment]
After installing Python, you could use: `python windows/helper.py patch_version`. And `python windows/helper.py show_version` if you want to get the version to set a variable.

**Comment by benoit-pierre** [comment]
OK, I lied... Using `windows/helper.py` will not work on Mac OS X, but I can make it work if you want?

**Comment by morinted** [comment]
I'd appreciate it!

**Comment by benoit-pierre** [comment]
OK, I moved the version stuff to `setup.py`:

```shell
> ./setup.py patch_version
running patch_version
> ./setup.py --version
2.5.8+336.gc5c8f2c
```

**Comment by morinted** [comment]
You've already tested this in your branch, so until we push a weekly there'll be no way to tell that it works for sure without trying it. Merge now, I guess we'll try it after getting the OSX one in.

**Pull request merged**
