### PR TITLE
Update to f-strings

### PR DESCRIPTION
**Pull request by cub525**
## Summary of changes
Superficial refactoring, no actual code change.

This is my first PR, so I don't know if I need to add a news snippet, the directions didn't say anything about those for refactors.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
A strong -1 on any kind of pep8 auto-formatting (the added newlines).

Why change only one of the `%` interpolations to use a f-string, and not the others? This feel really random.

**Comment by user202729** [comment]
I don't think this is necessary or desirable.

**Comment by cub525** [comment]
Got it, it doesn't say anywhere I could read that Autopep8 was discouraged. As I mentioned, this is my first pull request, and I just didn't notice the other `%` interpolations, because I was not paying enough attention

**Comment by cub525** [comment]
Fixed issues as mentioned by @benoit-pierre.

**Review by benoit-pierre — APPROVED** [review]

**Comment by cub525** [comment]
Alright, Now that I've done it once, I'll tackle the larger project of getting it to be standard across all the files.

**Pull request closed without merging**
