### PR TITLE
Rewrite keyboard emulation for Windows

### PR DESCRIPTION
**Pull request by morinted**
The keyboard emulation through SendKeys had some issues. Namely, it was not possible to emulate Windows key or a lot of special keys. It also didn't emulate keys, rather it sent characters to the foreground application.

I have rewritten the emulation using SendInput, which is a little more low-level. It can emulate most keys on the OS level, and it uses CTypes. It also has support for outputting Unicode characters using VK_PACKET. For more information, the commit messages have details surrounded around the various commits.

### CODE REVIEW

**Comment by morinted** [comment]
Is there anything I can do to help you with this pull request? I've been using it since November and it really does work better in general in terms of program compatibility on Windows.

**Comment by shayneholmes** [comment]
I've built this independently and verified that it works with Z-Type at least (fun!), and doesn't appear to break anything else. My use cases include terminal services (remote desktop), universal apps on windows 10 preview, and a lot of free form writing in WriteMonkey. +1 for this change!

**Comment by morinted** [comment]
Thanks Shayne,

I should add that I have used this change for the months since releasing
it, and have had no issues, and do benefit from additions like media keys,
the use of the Windows key, on top of the increased application support.

Ted

**Comment by mighele** [comment]
Hi Ted.

I've just tested this and it doesn't seem to work with a UK keyboard layout. I have a dictionary entry for "That's" and "It's" and it shows them as "That#s" and "It#s".

I also gave it a test with a French keyboard layout and the results were "That²s" and "It²s".

Thanks
Mike

**Comment by morinted** [comment]
Right, because this emulates the physical pressing of keys, that makes
sense. That's a big shame. I wonder if there's a way to reconcile the
benefits of each method.

**Comment by balshetzer** [comment]
I seem to remember that there is a Windows API for accessing the keyboard
layout. Then you can use your method for keys available on the keyboard by
using keycodes and falling back to the old method for chars not on the
current keyboard.

**Comment by morinted** [comment]
@mighele I think that non-US layouts should work on this now, so you should try it out :)

Also, this is ready for review. Please scrutinize away. (pinging also @chajadan)

I've also made a build for anyone who just wants to try it without actually building: https://www.dropbox.com/s/lp2q77mapulekkq/plover.exe?dl=0

**Comment by morinted** [comment]
Playing around some more, I think that:

- the global manipulating function needs to add not found characters to the key name to Unicode list.
- we might consider changing Alt-Gr characters to Unicode only, because Alt-Gr can have some weird effects (like the effects of ` and ^ are weird because when Alt-Gr'd, they are supposed to be used as accents)

I will be investigating this tonight.

**Comment by morinted** [comment]
I've got some work to do on this, going to clean up the variables a little bit and try to simplify things, then flatten the history. Overall, though, I still find myself needing this change in my day-to-day on Windows.

**Comment by morinted** [comment]
@benoit-pierre I rewrote it. Try it out! :D

**Pull request merged**
