### PR TITLE
Adds multiple suggestions to Suggestions window

### PR DESCRIPTION
**Pull request by balthamos**
See #264 for more details.

### CODE REVIEW

**Comment by morinted** [comment]
When there are no suggestions, it displays last word as "N/A". It would be nice to see the word that it can't match. Because if my dictionary doesn't have FlowType in it, I'd like to see "FlowType: no suggestions" instead of "N/A: no suggestions". This will help users decide when it's time to add a new dictionary entry.

**Comment by balthamos** [comment]
I went ahead and changed "Last Word" to always show the last stroked word.

Ellipses do work for me, though it only suggests HR-PZ (and also "last word" displays "." instead of "..."). 

The reason that SKWR-RBGS does not show up is because it is defined as "{^...}{ }{-|}", which is too complicated to be interpreted by the current lookup logic.

**Comment by morinted** [comment]
I'll build and use it during the day tomorrow before pulling. I've got to
say, it's really awesome. Changes the way I feel about the default
dictionary. Thanks so much for these changes.

**Comment by morinted** [comment]
Nitpicking -- could you reword your commit message on 0d5e8b5b50 to say "264" instead of "246"? Building now and I'll pull tonight.

**Comment by balthamos** [comment]
Glad I was able to contribute something useful :). Commit message should now reference the correct issue.

Also, the reason it is picking up HR-PZ but not HR-PS is because HR-PS is `"..."` and HR-PZ is `". . ."` (has spaces between the dots).

The current word detection logic uses this regular expression `'[-\'"\w]+|[^\w\s]'` to figure out what is a word and what isn't. It does not consider `.` to a part of the same word, always separate. So `...` is never constructed as a "word" by the suggestion logic.

**Comment by morinted** [comment]
Right, I get what you mean. All right, well, thanks so much for these changes. I'll probably get to styling sometime soon with an HTML list box.

**Pull request merged**
