### PR TITLE
Fix launch.sh to work on macOS

### PR DESCRIPTION
**Pull request by benoit-pierre**
No `readlink -e` on macOS.

### CODE REVIEW

**Comment by morinted** [comment]
We should probably apply a similar change to test.sh

**Comment by benoit-pierre** [comment]
Maybe we should just assume `test.sh` is always run from the source directory? Unlike `launch.sh`, I don't see being able to symlink it somewhere in `$PATH` as a use-case we want to support.

**Comment by morinted** [comment]
Agreed, so it'll just be the removal of the readlink?

**Comment by benoit-pierre** [comment]
Yes, like `bootstrap.sh`, `test.sh` would need to be run from the source directory.

**Pull request merged**
