### PR TITLE
 make sure main window is placed within screen boundaries

### PR DESCRIPTION
**Pull request by benoit-pierre**
+ one additional minor cleanup

### CODE REVIEW

**Comment by morinted** [comment]
Awesome work! Just a couple questions:

- Can I ask you to expand a little bit on how this fixes the problem?
- Is it true that other GUI windows are not protected (or are they since they will have config values loaded unlike the main frame?)
- Does this need testing on OSX and Windows?

**Comment by benoit-pierre** [comment]
The call to `self.SetRect(AdjustRectToScreen(...))` is already present for other windows. The problem with the main one was the call to `self.SetPosition(...)` after (plus the fact that the configuration is loaded during the init, so we can't use it right away).

I tested on Linux, and the Windows version with Wine.

**Comment by benoit-pierre** [comment]
To be clear, the goal is to fix the case when config values are out of bounds (e.g. you send you config to someone using a smaller screen size).

**Comment by morinted** [comment]
Thank you for testing it. I'll build this and try to break it on OS X.
Expect a merge tomorrow if all goes well.

One case that I see fixing is bogus values getting read in. I'll try with
the config set with -32000 X and Y as that happened sometimes. See #133

**Comment by benoit-pierre** [comment]
Yes, this fix this case too.

**Comment by morinted** [comment]
Thanks again Ben, another great commit. I appreciate it a lot.

**Pull request merged**
