### PR TITLE
Add translation into Spanish

### PR DESCRIPTION
**Pull request by nvdaes**
## Summary of changes

Closes 

### Pull Request Checklist
- [ ] Changes have tests
- [x] News fragment added in news.d. See [documentation](https://github.com/openstenoproject/plover/blob/master/doc/developer_guide.rst#making-a-pull-request) for details

### CODE REVIEW

**Comment by nvdaes** [comment]
Thanks for maintaining Plover. Here's translation into Spanish:

- Changes don't have test since this is not code, just a .po file.
- News fragment isn't added in news.d, since there's no section about localization and the program is only translated into French.

Please let me know if anything else needs to be done from my part.

**Comment by user202729** [comment]
The `&` in the strings are for the keyboard shortcut (underlined character in the menu)

If you make two of them have the same underlined character (`"&Editar diccionarios"` and `"&Eliminar diccionarios"`), it's not very efficient or might not work properly.

**Comment by nvdaes** [comment]
Thanks @user202729. I'll fix conflicts in shortcuts.

**Comment by nvdaes** [comment]
Pot file isn't updated and some messages are not added to the .po file.
Will wait for an update of the translation template or further instructions. Anyway, I'm not register in CircleCI and cannot see what's the failure.
Thanks

**Comment by benoit-pierre** [comment]
Thanks for your patience, #1209 will update the catalog.

> News fragment isn't added in news.d, since there's no section about localization and the program is only translated into French

A new `news.d/feature/1165.ui.md` news fragment would make sense: `Add Spanish translation.`.

> Anyway, I'm not register in CircleCI and cannot see what's the failure.

We've switched to Github Actions, so that should not be an issue anymore.

**Comment by nvdaes** [comment]
Thank you, @benoit-pierre. 
I've added the requested news fragment and now all check pass (1 skypped). Please let me know if I should make any other change or feel free to merge when appropriate.
Kind regards

**Comment by benoit-pierre** [comment]
Well, I should have been clear that #1209 has not yet been merged, so I have force-updated you branch with the changes in #1209, and updated the Spanish translation catalog. If you could force-pull on your side, and fix those translations that need to be updated, then once #1209 is merged we can merge this without further work.

**Comment by nvdaes** [comment]
Hello, I've performed a local reset --hard to set the repo updated to your changes and then I've translated pending messages and reviewed translations. Of course, if I detect messages that need to be improved in my daily work, I'll create a PR to enhance the spanish translation. Feel free to merge or let me know if something needs to be done before.
Thanks a lot.

**Comment by nvdaes** [comment]
Thanks for merging and for all your excellent work.

**Pull request merged**
