### PR TITLE
Do not remove filters on dictionaries reload

### PR DESCRIPTION
**Pull request by user202729**
## Summary of changes

Closes https://github.com/openstenoproject/plover/issues/1381 .

*(is the approach okay? I don't think there's any other instance in Plover code that the filter feature is used)*

### Pull Request Checklist
- [ ] Changes have tests
- [ ] News fragment added in news.d. See [documentation](https://github.com/openstenoproject/plover/blob/master/doc/developer_guide.md#making-a-pull-request) for details

### CODE REVIEW

**Comment by user202729** [comment]
I'm not sure if the fail is a problem of the test or the code. Does the hook expect that the objects will never have the dicts modified?

**Comment by benoit-pierre** [comment]
Yes, just:
```diff
 plover/engine.py | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

diff --git i/plover/engine.py w/plover/engine.py
index 1b77dba8..21489a1d 100644
--- i/plover/engine.py
+++ w/plover/engine.py
@@ -175,9 +175,8 @@ def dictionaries_changed(l1, l2):
         if not dictionaries_changed(dictionaries, self._dictionaries.dicts):
             # No change.
             return
-        self._dictionaries = StenoDictionaryCollection(dictionaries)
-        self._translator.set_dictionary(self._dictionaries)
-        self._trigger_hook('dictionaries_loaded', self._dictionaries)
+        self._dictionaries.set_dicts(dictionaries)
+        self._trigger_hook('dictionaries_loaded', StenoDictionaryCollection(dictionaries))
 
     def _update(self, config_update=None, full=False, reset_machine=False):
         original_config = self._config.as_dict()
```
and leave the test alone.

**Comment by user202729** [comment]
On the other hand, if it's done like that the hook argument will not have the filters set.

Perhaps the safest way would be...

```python
        old_filters = self._dictionaries.filters
        self._dictionaries = StenoDictionaryCollection(dictionaries)
        self._dictionaries.filters = old_filters
        self._translator.set_dictionary(self._dictionaries)
```

it's mainly annoying because `StenoDictionaryCollection` init doesn't take `filters` as input. Make it an optional argument is also an option.

------

Another option is to make `dicts` completely immutable, and remove `set_dicts` method entirely (while leaving `add_filter` / `remove_filter` intact)

**Comment by benoit-pierre** [comment]
We don't want access to the dictionaries through the hook arguments, so ideally, we just notify a collection of steno-dict like object, with just the right information for monitoring the status of the dictionaries (names / paths, read-only state, wether each dictionary was successfully loaded or not, ...).

**Review by benoit-pierre — CHANGES_REQUESTED** [review]
This just need a news entry.

**Comment by user202729** [comment]
Done (not sure if the wording is clear enough however)

**Review by benoit-pierre — APPROVED** [review]

**Pull request merged**
