### PR TITLE
Add Spanish translation of readme.

### PR DESCRIPTION
**Pull request by stanographer**
To reach a wider audience, I think our documentation should be multilingual. I'm submitting my translation of it into Spanish :]. I can add more languages in the future if this is something we want to do.

### CODE REVIEW

**Comment by morinted** [comment]
@stanographer I'm currently rewriting the documentation and the Plover guide. Would you be willing to work with me to have a Spanish translation on day 1 of the updated docs?

**Comment by stanographer** [comment]
I'd be certainly willing to help with that! 

S

Stanley Sakai, CRC, CSR
Certified Shorthand Reporter
Notary Public
Superlative Realtime, New York, NY
(212) 390-1607

Sent from my Sony Xperia™ smartphone

---- Ted Morin schreef ----

**Comment by morinted** [comment]
In the meanwhile, I'll consider adding this. I'd rather include it as a
link near the top of the English doc. What would you recommend as link
text? I doubt the Spanish speakers would want to click "Read this in
Spanish!" :p

**Comment by stanographer** [comment]
For link text make it "Leer esta página en Español". 

Stanley Sakai, CRC, CSR
Certified Shorthand Reporter
Notary Public
Superlative Realtime, New York, NY
(212) 390-1607

Sent from my Sony Xperia™ smartphone

---- Ted Morin schreef ----

**Comment by stanographer** [comment]
Or "Haga clic aquí para leer esta página en Español". That one might be better. 

Stanley Sakai, CRC, CSR
Certified Shorthand Reporter
Notary Public
Superlative Realtime, New York, NY
(212) 390-1607

Sent from my Sony Xperia™ smartphone

---- Ted Morin schreef ----

**Comment by stanographer** [comment]
Oh, wow that looks so annoying when I reply via email with my sig and all that.

**Comment by morinted** [comment]
Hah, it's all right. I've updated the home page with the link at the top of the file. The only problem I see with translation is the versioning. We'd need to keep translators on the line for when changes occur. But for now this is a nice addition. Thanks.

**Comment by stanographer** [comment]
When do you think you could get me the first bits of the rewrite to tran?

---- Ted Morin schreef ----

**Comment by stanographer** [comment]
I can defo lend a hand in translation as well as keeping tabs on versioning, to make sure all the docs are consistent across the languages.

---- Ted Morin schreef ----

**Comment by morinted** [comment]
All right. I'll push to a branch once I've updated the Plover guide, to
start, then notify you then. The rest will come with time, and will evolve
in the tasks outlined in Plover-next in the github issues.

**Pull request merged**
