### PR TITLE
oslayer/config: improve check for pkg_resources support

### PR DESCRIPTION
**Pull request by benoit-pierre**

### CODE REVIEW

**Comment by morinted** [comment]
Is your build.py script going to come into play in another PR? This one still gives the file exists warning.

**Comment by morinted** [comment]
To be clear, I don't think this PR fixed what you wanted it to. This is what I get on launch:

Plover Error Screenshot

**Comment by benoit-pierre** [comment]
That's with pyinstaller 2.1, it works with 3.0.

**Comment by morinted** [comment]
Ah, of course it is. Maybe we should write in to the dev instructions that it's `pip install pyinstaller==3.0` for explicitness. Thanks for fixing this though.

**Pull request merged**
