### PR TITLE
travis ci integration test

### PR DESCRIPTION
**Pull request by benoit-pierre**

### CODE REVIEW

**Comment by morinted** [comment]
I was able to add `install: "pip install svn+https://svn.code.sf.net/p/python-xlib/code/trunk/"` to get python-xlib installed.

**Comment by benoit-pierre** [comment]
Yeah, I saw that. But I'm thinking all this stuff is unnecessary for the tests, so maybe add a magic environment variables that disable wxPython, python-xli, ... for use when testing with Travis.

**Comment by morinted** [comment]
Are you interested in me pulling this in? There's a typo (runing / running) in 62abb8b. Are you hoping to get the Stentura stuff resolved before pulling the changes?

**Comment by benoit-pierre** [comment]
Yes, let's wait for the Stentura stuff to get sorted out.

**Comment by morinted** [comment]
All right, since @Elktro is done with updating the tests, we can add the Travis support after you rewrite.

**Comment by morinted** [comment]
We'll close this in favor of the build systems.

**Pull request closed without merging**
