### PR TITLE
Training Tools

### PR DESCRIPTION
**Pull request by brentn**
Merge with latest master

### CODE REVIEW

**Comment by morinted** [comment]
@mighele @brentn Are you guys willing to continue working on this? It needs the local dict parameter as Mike pointed out, and then we can change the behavior of the box coming up, and then we can start testing. It also needs to be merged with the official branch because some of the features are already present now. Thoughts?

**Comment by brentn** [comment]
Hey Ted, thanks for asking.

I could use some help and even just another set of eyes on the code would
be helpful.  Right now it's mostly a lack of time for me.

**Comment by morinted** [comment]
I just ran this on OSX as is, and I'm having some problems. After opening the speed ticker, I'm no longer able to output capitals or backspace. The console, upon any backspacing, gives:

```
2015-11-11 9:37:47.848 AM Plover[1448]: Traceback (most recent call last):
2015-11-11 9:37:47.848 AM Plover[1448]:   File "wx/_core.pyc", line 16766, in <lambda>
2015-11-11 9:37:47.848 AM Plover[1448]:   File "plover/app.pyc", line 264, in _translate_stroke
2015-11-11 9:37:47.848 AM Plover[1448]:   File "plover/translation.pyc", line 120, in translate
2015-11-11 9:37:47.848 AM Plover[1448]:   File "plover/translation.pyc", line 278, in _translate_stroke
2015-11-11 9:37:47.848 AM Plover[1448]:   File "plover/translation.pyc", line 162, in _output
2015-11-11 9:37:47.848 AM Plover[1448]:   File "plover/formatting.pyc", line 94, in format
2015-11-11 9:37:47.849 AM Plover[1448]:   File "plover/formatting.pyc", line 165, in render
2015-11-11 9:37:47.849 AM Plover[1448]:   File "plover/formatting.pyc", line 128, in commit
2015-11-11 9:37:47.849 AM Plover[1448]:   File "plover/gui/predictions.pyc", line 98, in output_handler
2015-11-11 9:37:47.849 AM Plover[1448]:   File "plover/gui/predictions.pyc", line 60, in process
2015-11-11 9:37:47.849 AM Plover[1448]: AttributeError: 'dict' object has no attribute 'DeleteAllItems'
```

Can't open the stroke trainer, I get:

```
2015-11-11 9:39:37.833 AM Plover[1536]: Traceback (most recent call last):
2015-11-11 9:39:37.834 AM Plover[1536]:   File "plover/gui/config.pyc", line 546, in on_show_brief_suggestions
2015-11-11 9:39:37.834 AM Plover[1536]: TypeError: display() takes exactly 2 arguments (3 given)
```

Same with brief suggestions:

```
2015-11-11 9:40:39.070 AM Plover[1536]: Traceback (most recent call last):
2015-11-11 9:40:39.070 AM Plover[1536]:   File "plover/gui/config.pyc", line 546, in on_show_brief_suggestions
2015-11-11 9:40:39.070 AM Plover[1536]: TypeError: display() takes exactly 2 arguments (3 given)
```

Also saw, somewhere, `global name dictionary is not defined`

------

Not sure if these issues are OSX-specific, but I do remember the tools working on some builds before. If you want to lighten the load, we could submit one tool at a time. The brief trainer seems particularly useful, given that at the moment we have the suggestions window in Plover's code.

**Comment by morinted** [comment]
I'll close this for now, as we're focusing our efforts at some other core features. I welcome any further PRs if they are updated for the current master. Alternatively, it may be worth working on the existing Lookup and Suggestions tools. That, or separating the training tools into separate PRs so that there is less to review at once.

**Pull request closed without merging**
